-- Migration: Populate carton_size for existing products
-- Data source: productlist.csv
-- Note: Uses UPPER(TRIM()) for case-insensitive matching with slight whitespace variations

UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('BAKING POWDER 100G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('BAKING SODA 125G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('BAKING SODA 250G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('BAKING SODA 500G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('SALTED BLACK BEANS_ SUP 100G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('BREAD CRUMBS 100G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('BREAD CRUMBS 230G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('BREAD CRUMBS 500G');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('BREAD CRUMBS 1kg.');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('SWEET CREAM STYLE CORN 410G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('WHOLE KERNEL CORN 410G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('YOUNG CORN 410G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM CORNSTARCH 200G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('RAM CORNSTARCH 400G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('CORSTARCH 12X1kg');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('ALL PURPOSE FLOUR 200G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('ALL PURPOSE FLOUR 400G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DESICCATED COCONUT 100 G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DESICCATED COCONUT 200 G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('TROPICAL FRUIT COCKTAIL 432G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('TROPICAL FRIUT COCKTAIL 822G');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('TROPICAL FRUIT COCKTAIL 3060G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('HOTCAKE MIX 200G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('HOTCAKE MIX 400G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('ELBOW MACARONI 200G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('ELBOW MACARONI 400G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('ELBOW MACARONI 1 KG');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('SALAD MACARONI 200G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('SALAD MACARONI 400G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('SALAD MACARONI 1 KG');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('MUSHROOMS WHOLE 198G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MUSHROOMS WHOLE 400G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('MUSHROOMS PIECES @ STEMS 198G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MUSHROOMS PIECES @ STEMS 400G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('INSTANT OATS 200G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('INSTANT OATS 500G');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('SPAGHETTI SAUCE SWEET STYLE 500g');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('SPAGHETTI SAUCE SWEET STYLE 900g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('PREMIUM SPAGHETTI 400g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('PREMIUM SPAGHETTI 450G');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('PREMIUM SPAGHETTI 900KG');
UPDATE products SET carton_size = 10 WHERE UPPER(TRIM(name)) = UPPER('RAM BDL.SWEET 900g/PASTA 700g');
UPDATE products SET carton_size = 8 WHERE UPPER(TRIM(name)) = UPPER('BUNDLE PACK PASTA/ SWEET 1KG');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('SPAGHETTI SAUCE SWEET STYLE 250G');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('SPAGHETTI SAUCE SWEET STYLE 560G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('SPAGHETTI SAUCE SWEET STYLE 1K');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('RAM SPAG. SAUCE ITALIAN 250G');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('RAM SPAG. SAUCE ITALIAN 560G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('RAM SPAG. SAUCE ITALIAN 1K');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('RAM DRY PEAS');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('IODIZED SALT COARSE 500G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM GREEN PEAS - SUP 100G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('GREEN PEAS 225G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('GREEN PEAS 450G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('PORK AND BEANS SUP 100G');
UPDATE products SET carton_size = 50 WHERE UPPER(TRIM(name)) = UPPER('PORK AND BEANS 165G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('PORK AND BEANS 220G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('PORK AND BEANS 390G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM RAISINS- BOX 30 G');
UPDATE products SET carton_size = 96 WHERE UPPER(TRIM(name)) = UPPER('RAM RAISINS - SACHET 50G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM RAISINS 100G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('RAM RAISINS 200G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM IODIZED SALT 250G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('RAM IODIZED SALT 500G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('RAM IODIZED SALT 1KG');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('TOMATO PASTE- SACHET 70 G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TOMATO PASTE- SUP 150G');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('TOMATO PASTE -SUP 500G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('TOMATO PASTE -SUP 1KG.');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE- FILIPINO STYLE 115G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE- FILIPINO STYLE 250G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE- FILIPINO STYLE 1K');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE SUP 115G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE SUP 200G');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE SUP 250G');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('TOMATO SAUCE-SUP 1K');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM HOT SAUCE 100ML');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('RAM SWEET PCKLE RELISH 100G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('RAM PICKLE RELISH 135G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('RAM PICKLE WHOLE 135G');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('HOT SAUCE 1gl');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('RAM SWEET PICKLE RELISH 3700G');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SEVILLA DRY PEAS');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('SEVILLA PICKLE RELISH 3700G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MITRA PALM OIL 485ml');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('MITRA PALM OIL 950ml');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('OYSTER SAUCE 72x70g');
UPDATE products SET carton_size = 144 WHERE UPPER(TRIM(name)) = UPPER('OYSTER SAUCE 144x30g');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('MASTER FLOORWAX RED 90g');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('MASTER FLOORWAX DYE WAX 90g');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('MASTER FLOORWAX COLORLESS');
UPDATE products SET carton_size = 150 WHERE UPPER(TRIM(name)) = UPPER('STARCH POWDER');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('MISUA 12''s');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('ODONG 12''s NEW');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('KAONG RED 8oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('KAONG GREEN 8oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('KAONG RED 12oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('KAONG GREEN 12oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('NATA DE COCO RED 8oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('NATA DE COCO GREEN 8oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('NATA DE COCO WHITE 8oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('NATA RED 12oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('NATA GREEN 12oz');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('NATA WHITE 12oz');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('KAONG RED 24oz');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('KAONG GREEN 24oz');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('NATA RED 24oz');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('NATA GREEN 24oz');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('NATA WHITE 24oz');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('NATA RED 32OZ');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('NATA GREEN 32OZ');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('TRU MAYO 200ml');
UPDATE products SET carton_size = 8 WHERE UPPER(TRIM(name)) = UPPER('TRU MAYO 1.8L');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('TRUMAYO 3.5L');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('YUMMEE PUDDING');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('YUMMEE JELLY');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE PAPAYA WIPES');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE SCENTED');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE SWEET DELIGHT');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE BABY WIPES UNSCENTED');
UPDATE products SET carton_size = 36 WHERE UPPER(TRIM(name)) = UPPER('T.L ALOEVERA single');
UPDATE products SET carton_size = 9 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE PAPAYA 3+1');
UPDATE products SET carton_size = 9 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE SWEET DELIGHT 3+1');
UPDATE products SET carton_size = 9 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE SCENTED 3+1');
UPDATE products SET carton_size = 9 WHERE UPPER(TRIM(name)) = UPPER('TENDER LOVE UNSCENTED 3+1');
UPDATE products SET carton_size = 9 WHERE UPPER(TRIM(name)) = UPPER('T.L ALOEVERA 3+1');
UPDATE products SET carton_size = 150 WHERE UPPER(TRIM(name)) = UPPER('KOJIC SOAP');
UPDATE products SET carton_size = 150 WHERE UPPER(TRIM(name)) = UPPER('KOJIC SOAP GLUTHA');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('RED FALCON MALLORCA 24x350ml');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('RED FALCON MALLORCA 12x750ml');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SOY SAUCE 3.8L');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SOY SAUCE 1.9ltr');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SOY SAUCE 1000ml w/HANDLE');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SOY SAUCE 385ml');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SOY SAUCE 200ml');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SOY SAUCE 100ML');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('CAMEL SUKANG PUTI 200ml');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('SUKA PUTI 12x1ltr');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('WHITE HOUSE BLACK BEANS 120g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('CAMEL BLACK BEANS 60g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('CAMEL BLACK BEANS 100g');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('CHOYO CHOYO CHOCO');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('CHOYO CHOYO UBE');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('CHOYO CHOYO STRAWBERRY');
UPDATE products SET carton_size = 96 WHERE UPPER(TRIM(name)) = UPPER('TOILY B. T. SINGLE X 96');
UPDATE products SET carton_size = 96 WHERE UPPER(TRIM(name)) = UPPER('HELLO BATH. TISSUE SINGLE');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('HELLO BATH. TISSUE X4');
UPDATE products SET carton_size = 8 WHERE UPPER(TRIM(name)) = UPPER('HELLO BATHROOM TISSUE 8 x 12');
UPDATE products SET carton_size = 80 WHERE UPPER(TRIM(name)) = UPPER('FOLDED TBL NAP 50''s 80');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('CHOCO JOY');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('CHAMPI');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('YAKEE');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('PINTORA');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FRUTOS ORIG');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FRUTOS SAMPALOK');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FRUTOS STRAWBERRY');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FRUTOS TROPICAL');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FRUTOS MILK');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('V FRESH');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FROOTY RAINBOW POP');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FROOTY CHOCO POP');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('FROOTY BUBBLE POP');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('FROOTY POP JAR');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('POTCHI PACK STRAWBERRY');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('MONAMI STRAWBERRY');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('MONAMI BUTTER');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('BUTTER KIST');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('I COOL RED');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('I COOL BLUE');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('JUMBO JAR');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('CHERRI JUMBO JAR');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('JUMBO CRAYON');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('JUMBO DINO EGGS');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('POTCHI HOLA HOOP');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('POTCHI GUMMI WORM');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('POTCHI BURGER');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('OTSO CHOCO');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('OTSO VANILLA');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('OTSO STRAWBERRY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('CHOQUICK');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('MY BIDA');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('CHOQUICK CHOCO BAR');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('LUV LUV CHOCO BAR');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('TOPIKO CHOCO BAR');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('MALLOWS CHOCO');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('MALLOWS SBERRY');
UPDATE products SET carton_size = 18 WHERE UPPER(TRIM(name)) = UPPER('MALLOWS PEACH MANGO');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('COOKS BANANA CATSUP 1gl.');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('COOKS BANANA CATSUP HALF gl.');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('COOKS CATSUP 1LTR');
UPDATE products SET carton_size = 35 WHERE UPPER(TRIM(name)) = UPPER('COOKS CATSUP POUCH');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('DIP HOT SAUCE 1gl.');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('EGGY MAYO 1gl.');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('EGGY MAYO 1ltr.');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('SNF PREMIUM MAYO 1gl.');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('SNF PREMIUM MAYO 1.7ltrs');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('SNF PREMIUM MAYO 1ltr');
UPDATE products SET carton_size = 50 WHERE UPPER(TRIM(name)) = UPPER('LA MIA HOT & SPICY');
UPDATE products SET carton_size = 50 WHERE UPPER(TRIM(name)) = UPPER('LA MIA FLAKES N OIL');
UPDATE products SET carton_size = 50 WHERE UPPER(TRIM(name)) = UPPER('LA MIA AFRITADA');
UPDATE products SET carton_size = 112 WHERE UPPER(TRIM(name)) = UPPER('PEANUT BUTTER 230g');
UPDATE products SET carton_size = 90 WHERE UPPER(TRIM(name)) = UPPER('PEANUT BUTTER 250g');
UPDATE products SET carton_size = 60 WHERE UPPER(TRIM(name)) = UPPER('PEANUT BUTTER 300g');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY FRUIT TREATS CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY MENTHOL CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY CHERRY MENTHOL CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY HONEY LEMON CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY MELON LOVE CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY COLA CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY FRUIT POP (LOLLIPOP) CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY CHOCO (LOLLIPOP) CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY COLA POP (LOLLIPOP) CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY COCONUT CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY RAINBOW CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY MANGO CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY SAMPALOK (TAMARIND) CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY UBE CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('JOLLY CAPPUCCINO CANDY');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('KYANDE SOFT CHEWY CANDY');
UPDATE products SET carton_size = 16 WHERE UPPER(TRIM(name)) = UPPER('ICE FRUITEE-BIG');
UPDATE products SET carton_size = 20 WHERE UPPER(TRIM(name)) = UPPER('ICE FRUITEE - MINI POPS');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('DAIRY HILL CREAMYSADA');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('DAIRY HILL POWDER');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('DAIRY HILL POWDER MILK 9+3');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('VEGA CORN STICKS CHEESE 8.5g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('VEGA CORN STICKS ROASTED 8.5g');
UPDATE products SET carton_size = 30 WHERE UPPER(TRIM(name)) = UPPER('FRUIT FIESTA');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SENORITA SAR. GREEN REG. 100/155g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SENORITA SAR. RED REG. 100/155g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SENORITA SAR.GREEN EASY OPEN 155g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SENORITA SAR. RED EASY OPEN 155g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SENORITA DRY PEAS 155g');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('SENORITA BLACK BEANS 110g');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('SENORITA BLACK BEANS 180g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MAYON CREAMSTYLE CORN 425g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MAYON WHOLE KERNEL 425g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MAYON MUSHROOM P/S 400G');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MAYON MUSHROOM WHOLE 400G');
UPDATE products SET carton_size = 100 WHERE UPPER(TRIM(name)) = UPPER('MAYON DRY PEAS 155g');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('MAYON GREEN PEAS 225g');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('MAYON GREEN PEAS 450g');
UPDATE products SET carton_size = 10 WHERE UPPER(TRIM(name)) = UPPER('PRAN MALT & MILK BISCUITS');
UPDATE products SET carton_size = 10 WHERE UPPER(TRIM(name)) = UPPER('PRAN NICE COCONUT BISCUITS');
UPDATE products SET carton_size = 10 WHERE UPPER(TRIM(name)) = UPPER('PRAN GLUCOSE BISCUITS');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('CLUB FRUITFUN ORANGE CREAM BISCUITS');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('CLUB FRUITFUN P/APPLE CREAM BISCUITS');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('CLUB FRUITFUN SBERRY CREAM BISCUITS');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('BISK CLUB SHERO CREAM BISCUITS');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('PRAN OH CAKE CHOCO MILK FLAVOR');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('PRAN OH CAKE BANANA FLAVOR');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('PRAN EASY INSTANT NOODLE CHICKEN');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('PRAN EASY INSTANT NOODLE BEEF');
UPDATE products SET carton_size = 40 WHERE UPPER(TRIM(name)) = UPPER('PRAN LOLLIPOP ASSORTED');
UPDATE products SET carton_size = 120 WHERE UPPER(TRIM(name)) = UPPER('PRAN CHOCO VANILLA LIQUID PASTE');
UPDATE products SET carton_size = 120 WHERE UPPER(TRIM(name)) = UPPER('PRAN MILKY LIQUID PASTE');
UPDATE products SET carton_size = 15 WHERE UPPER(TRIM(name)) = UPPER('PRAN CHEWY CANDY ORANGE FLAVOR JAR');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('PRAN CHEWY BLACK CURRANT POUCH');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('PRAN CHEWY CANDY ORANGE POUCH');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DRINKO FLOAT SBERRY W/ C. 330ML');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DRINKO FLOAT SBERRY W/ C.250ML');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DRINKO FLOAT P/APPLE W/ C. 250ML');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DRINKO FLOAT P/APPLE W/ C. 330ML');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DRINKO FLOAT LICH W/ C. 330ML');
UPDATE products SET carton_size = 24 WHERE UPPER(TRIM(name)) = UPPER('DRINKO FLOAT ORANGE W/ C. 330ML');
UPDATE products SET carton_size = 16 WHERE UPPER(TRIM(name)) = UPPER('TRUE MILK YOUGURT MILK DRINK 80ML');
UPDATE products SET carton_size = 16 WHERE UPPER(TRIM(name)) = UPPER('TRUE MILK STRAWBERRY MILK DRINK 80ML');
UPDATE products SET carton_size = 16 WHERE UPPER(TRIM(name)) = UPPER('TRUE MILK MANGO MILK DRINK 80ML');
UPDATE products SET carton_size = 16 WHERE UPPER(TRIM(name)) = UPPER('TRUE MILK GREEN APPLE MILK DRINK 80ML');
UPDATE products SET carton_size = 48 WHERE UPPER(TRIM(name)) = UPPER('ABLE FARM CONDENSED MILK 380g');
UPDATE products SET carton_size = 12 WHERE UPPER(TRIM(name)) = UPPER('SUKA PUTI 1ltr');
UPDATE products SET carton_size = 6 WHERE UPPER(TRIM(name)) = UPPER('SUKA PUTI 1.9ltr');
UPDATE products SET carton_size = 4 WHERE UPPER(TRIM(name)) = UPPER('SUKA PUTI 3.8ltr');
UPDATE products SET carton_size = 72 WHERE UPPER(TRIM(name)) = UPPER('SUKA PUTI 100ml');
